version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: log_records_database_container
    restart: always
    environment:
      MYSQL_DATABASE: 'log-records'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local